# Load Zsh-specific startup files
for zsh in ~/.config/zsh/zshrc.d/*.zsh(N) ; do
    [[ -e $zsh ]] || continue
    source "$zsh"
done

export PATH="/home/vhodh/.local/bin":$PATH

eval "$(starship init zsh)"
